just first try
ODmain/java-explore-with-me pull request #1
Opened 2024-05-22 14:43 UTC by ODmain

2024-05-23 15:45 UTC, db-exp requested changes

2024-05-23 15:45 UTC, db-exp commented on statistics-service/dto/src/main/java/ru/practicum/dto/StatisticsInputHitDto.java
> +    @NotNull(message = "Cannot be null or empty")
тогда NotBlank

2024-05-23 15:45 UTC, db-exp commented on statistics-service/dto/src/main/java/ru/practicum/dto/StatisticsInputHitDto.java
> +    @NotNull(message = "Cannot be null or empty")
тогда NotBlank

2024-05-23 15:45 UTC, db-exp commented on statistics-service/dto/src/main/java/ru/practicum/dto/StatisticsInputHitDto.java
> +    @NotNull(message = "Cannot be null or empty")
тогда NotBlank

2024-05-23 15:45 UTC, db-exp commented on statistics-service/dto/src/main/java/ru/practicum/dto/StatisticsInputHitDto.java
> +    @NotNull(message = "Cannot be null or empty")
тогда NotBlank

2024-05-23 15:45 UTC, db-exp commented on statistics-service/service/src/main/resources/schema.sql
> +    ip VARCHAR(300) NOT NULL,
много прям, там 40 достаточно

2024-05-23 15:45 UTC, db-exp commented on statistics-service/service/src/main/resources/schema.sql
> +    app VARCHAR(300) NOT NULL,
тоже, кажется, многовато

2024-05-23 16:33 UTC, ODmain commented on statistics-service/dto/src/main/java/ru/practicum/dto/StatisticsInputHitDto.java
> +    @NotNull(message = "Cannot be null or empty")
с NotBlank все тесты валятся

2024-05-24 08:55 UTC, db-exp approved these changes

2024-05-24 08:55 UTC, db-exp commented on statistics-service/dto/src/main/java/ru/practicum/dto/StatisticsInputHitDto.java
> +    @NotNull(message = "Cannot be null or empty")
Тогда size не нужен для NotNull) ок

2024-05-24 09:10 UTC, merged